// frontend/src/views/login.vue
<template>
  <main class="main main--connect">
    <form @submit.prevent="login()" class="w-75 align-items-center form-block d-flex m-auto shadow rounded">
      <div
        class="form-block--left d-flex flex-column justify-content-center block-demi-container p-3 text-right align-self-stretch"
      >
        <img class="logo align-self-end" src="../assets/icon.svg" alt="Logo Groupomania" />
        <p>
          <small>
            Vous n'avez pas encore de compte,
            <router-link class="redirection-singup" to="/signUp">enregistrez-vous</router-link>
          </small>
        </p>
      </div>
      <div class="block-demi-container p-3">
        <div class="form-group">
          <label for="inputUsername">Email</label>
          <input type="email" class="form-control" id="inputEmail"  v-model="email" />
        </div>
        <div class="form-group">
          <label for="inputPassword">Password</label>
          <input
            type="password"
            class="form-control"
            id="inputPassword"
            v-model="password"
          />
        </div>
        <button type="submit" class="btn btn-primary">Connexion</button>
      </div>
    </form>
  </main>
</template>

<script>
import axios from "axios"
export default {
  name: "Login",
  data() {
    return {
      email: "",
      password: "",
      error: false,
    };
  },
  methods: {
    login() {
      this.error = false;
      axios.post(
          "http://localhost:3000/api/user/login",
          {
            email: this.email,
            password: this.password,
          },
          {
            headers: {
              "Content-Type": "application/json",
            },
          }
        )
        .then((user) => {
          console.log( user.data.data.isAdmin);
          localStorage.setItem("user", JSON.stringify(user.data)); // envoie de données dans le localstorage
          localStorage.setItem("pseudo", user.data.data.pseudo);
          localStorage.setItem("email", user.data.data.email);
          localStorage.setItem("id", user.data.data.id);
          localStorage.setItem("isAdmin",user.data.data.isAdmin);                               
          localStorage.setItem("imgProfil", user.data.data.imgProfil);
          localStorage.setItem("poste", user.data.data.poste);
          localStorage.setItem("token", user.data.token);
          this.$router.replace("/home");
        })
        .catch((e) => {
          alert(e.response.data.message);
          this.error = e.response.data.message.replace("Validation error:", "");
        });
    },
  },
};
</script>

<style lang="scss">
    @import "./src/scss/global.scss";
</style>

// frontendd/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import {Router} from "@angular/router";
import {UserModelResponse} from "../../models/user-response.model";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  emailControl: FormControl = this.fb.control('', Validators.required);
  get mail (): string {
   return this.emailControl.value
  }
  set mail (email: string) {
    this.emailControl.setValue(email);
  }
  motPassControl: FormControl = this.fb.control('', Validators.required);
  get motPass (): string {
   return this.motPassControl.value
  }
  set motPass (email: string) {
    this.motPassControl.setValue(email);
  }
  addressForm = this.fb.group({
    email: this.emailControl,
    motPass: this.motPassControl,
  });

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
    private route: Router,
    ) {}

  login(): void {
    this.http.post<UserModelResponse>('http://localhost:3000/api/user/login',
      {
        email: this.mail,
        password: this.motPass,
      },
      {
        headers: {
          "Content-Type": "application/json",
        }
      }
    ).subscribe(user => {
      console.log(user.token)
      localStorage.setItem("token", user.token);
      this.route.navigate(['/home'])
    })
  }

  ngOnInit(): void {
  }

}

<div class="login-container">
  <div [formGroup]="addressForm" class="login-form">
    <div style="width: 300px; height: 100px; margin: 0 auto;">
      <img  alt="Logo" style="width: 100%; height: auto; margin-top: -40%;" src="../../../assets/icon-left-font-monochrome-black.png">
    </div>
    <div>
      <label>Mail</label>
      <input formControlName="email">
    </div>
    <div>
      <label>Mot de passe</label>
      <input formControlName="motPass">
    </div>
   <div style="display: flex; justify-content: end; margin-top: 5%">
    <span>
      Vous avez pas de compte? /
    </span>
    <a href="inscription">Inscription</a>
   </div>
    <div style="display: flex; justify-content: center; margin-top: 10%;">
      <button mat-stroked-button class="login-button "  (click)="login()">Connexion</button>
    </div>
  </div>
</div>
